language: android

jdk: oraclejdk8

android:
  components:
      - build-tools-26.1.0
      - android-26
      - sys-img-armeabi-v7a-android-tv-l
      - add-on
      - extra
  licenses:
      - 'android-sdk-preview-license-52d11cd2'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-28"

branches:
  only:
  - master

install:
  - chmod +x ./gradlew

script: ./gradlew clean assemble

notifications:
  email:
    on_success: change
    on_failure: always
